In [1]:
%cd ../src

/Users/jachym.solecky/Playground/ML/src


In [4]:
from pathlib import Path
import utils.image_utils as image_utils
from utils.config import get_config
import numpy as np
from sklearn.utils import shuffle

In [8]:
dataset_path = Path.expanduser(Path(get_config('train_folder')))
dataset_path = dataset_path.parent / 'deleted'
categories = get_config('categories')
n_cats = range(len(categories))
filenames = [list((dataset_path / category).glob('*')) for category in categories]
image_arrays = np.array([image_utils.load(str(filename)) for i in n_cats for filename in filenames[i]])
image_labels = np.concatenate([np.zeros(len(filenames[0])), np.ones(len(filenames[1]))])
transformed_image_arrays = np.array([image_utils.transform(image, []) for image in image_arrays])
rescaled_image_arrays = 1 - transformed_image_arrays * 1./255

print(rescaled_image_arrays, image_labels)
x, y = shuffle(rescaled_image_arrays, image_labels)
print(x)
print(x.shape)
print(y)

[[[[0.45882353 0.4627451  0.47843137]
   [0.45490196 0.45882353 0.47058824]
   [0.44705882 0.4627451  0.47058824]
   ...
   [0.54901961 0.56862745 0.58039216]
   [0.71372549 0.7372549  0.7372549 ]
   [0.89411765 0.90196078 0.90196078]]

  [[0.43921569 0.44705882 0.45490196]
   [0.43137255 0.43529412 0.44705882]
   [0.45882353 0.4627451  0.47058824]
   ...
   [0.4627451  0.46666667 0.49019608]
   [0.44313725 0.43921569 0.45882353]
   [0.45490196 0.45490196 0.47058824]]

  [[0.45098039 0.45490196 0.46666667]
   [0.44705882 0.45098039 0.4627451 ]
   [0.43529412 0.43921569 0.45490196]
   ...
   [0.42745098 0.43137255 0.44313725]
   [0.45098039 0.45490196 0.46666667]
   [0.43921569 0.44705882 0.45490196]]

  ...

  [[0.4745098  0.45098039 0.47058824]
   [0.47843137 0.45490196 0.4745098 ]
   [0.47843137 0.45490196 0.47843137]
   ...
   [0.57647059 0.59607843 0.62352941]
   [0.58431373 0.61176471 0.63529412]
   [0.57254902 0.60392157 0.62745098]]

  [[0.47058824 0.44705882 0.47058824]
   [0.4