In [29]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
from PIL import Image

In [73]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()
x_train = x_train[np.in1d(y_train, (1, 5))]
y_train = y_train[np.in1d(y_train, (1, 5))]
x_test = x_test[np.in1d(y_test, (1, 5))]
y_test = y_test[np.in1d(y_test, (1, 5))]
y_train[y_train == 5] = 0
y_test[y_test == 5] = 0

In [93]:
x_train = x_train / 255.0
x_test = x_test / 255.0

In [75]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(10000, 32, 32, 3)
(10000, 1)
(2000, 32, 32, 3)
(2000, 1)


In [76]:
Image.fromarray(x_test[1], mode="RGB").show()

In [88]:
model = keras.Sequential([
    keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(32, 32, 3)),
    keras.layers.MaxPooling2D((2,2)),
    keras.layers.Conv2D(64, (3,3), activation='relu'),
    keras.layers.MaxPooling2D((2,2)),
    keras.layers.Conv2D(64, (3,3), activation='relu'),
    keras.layers.Flatten(),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(2)
])

In [89]:
model.compile(
    optimizer=keras.optimizers.legacy.Adam(0.001),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy']
)

In [97]:
model.fit(x_train[:300], y_train[:300], epochs=10, validation_data=(x_test, y_test))

Epoch 1/10
10/10 [==============================] - 1s 139ms/step - loss: 0.0190 - accuracy: 0.9967 - val_loss: 0.0953 - val_accuracy: 0.9680
Epoch 2/10
10/10 [==============================] - 0s 40ms/step - loss: 0.0156 - accuracy: 0.9933 - val_loss: 0.0869 - val_accuracy: 0.9720
Epoch 3/10
10/10 [==============================] - 0s 39ms/step - loss: 0.0078 - accuracy: 1.0000 - val_loss: 0.0816 - val_accuracy: 0.9715
Epoch 4/10
10/10 [==============================] - 0s 38ms/step - loss: 0.0059 - accuracy: 1.0000 - val_loss: 0.0773 - val_accuracy: 0.9745
Epoch 5/10
10/10 [==============================] - 0s 42ms/step - loss: 0.0026 - accuracy: 1.0000 - val_loss: 0.0795 - val_accuracy: 0.9710
Epoch 6/10
10/10 [==============================] - 0s 39ms/step - loss: 0.0022 - accuracy: 1.0000 - val_loss: 0.0770 - val_accuracy: 0.9755
Epoch 7/10
10/10 [==============================] - 0s 39ms/step - loss: 0.0012 - accuracy: 1.0000 - val_loss: 0.0796 - val_accuracy: 0.9735
Epoch 8/10
1

In [98]:
model.evaluate(x_test, y_test, verbose=2)

63/63 - 0s - loss: 0.0783 - accuracy: 0.9775 - 284ms/epoch - 5ms/step


[0.07829855382442474, 0.9775000214576721]

In [99]:
print(y_test[0:5])
model(x_test[0:5])


[[1]
 [1]
 [0]
 [0]
 [0]]


<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-1.4690973 ,  0.33736795],
       [-6.1949034 ,  2.4544213 ],
       [ 3.4850748 , -2.6558356 ],
       [ 1.20736   , -1.641212  ],
       [ 8.415024  , -5.4924364 ]], dtype=float32)>